# Control file for continuous integration testing at http://travis-ci.org/

language: c
compiler:
  - gcc

os:
  - linux

env:
  global:
    - HTSDIR=./htslib

addons:
  apt:
    packages:
    - liblzma-dev
    - libbz2-dev

before_script:
  - git clone --depth=5 --branch=develop git://github.com/samtools/htslib.git
  - cd htslib && make && cd ..

script:
  - make -e && make test
